//TOKEN
export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const TOKEN_ERROR = "TOKEN_ERROR";
//UX
export const SET_GLITCH = "SET_GLITCH";

// Hisotry
export const SET_ENV = "SET_ENV";
export const GET_HISTORY_SEARCH = "GET_HISTORY_SEARCH";
export const HISTORY_SEARCH_LOADING = "HISTORY_SEARCH_LOADING";
export const HISTORY_DETAIL_LOADING = "HISTORYS_DETAIL_LOADING";
export const GET_HISTORY_DETAIL = "GET_HISTORY_DETAIL";
export const HISTORY_ERROR = "HISTORY_ERROR";
export const HISTORY_INPUT_ERROR = "HISTORY_INPUT_ERROR";
export const GET_HISTORY_DETAIL_ID = "GET_HISTORY_DETAIL_ID";
export const HISTORY_DETAIL_ID_LOADING = "HISTORY_DETAIL_ID_LOADING";
export const SET_BASIC_ANALYTICS = "SET_BASIC_ANALYTICS";
export const SET_FULL_ANALYTICS = "SET_FULL_ANALYTICS";
export const RESET_HISTORY = "RESET_HISTORY";
